name: Unittests & Auto-publish

# Allow to trigger the workflow manually (e.g. when deps changes)
on: [push, workflow_dispatch]

jobs:
  pytest-job:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3

    # Install deps
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: pip --version
    # As changes can be pushed to both etils and visu3d, we install etils from `main` branch
    # If modifying this, also modify `pyproject.toml`
    - run: pip install "etils[array_types,edc,enp,epath,epy,etree] @ git+https://github.com/google/etils"
    - run: pip install "dataclass_array @ git+https://github.com/google-research/dataclass_array"
    - run: pip install -e .[dev]
    - run: pip freeze

    # Run tests
    - name: Run core tests
      run: pytest -vv -n auto

  # Auto-publish when version is increased
  publish-job:
    # Only try to publish if:
    # * Repo is self (prevents running from forks)
    # * Branch is `main`
    if: |
      github.repository == 'google-research/visu3d'
      && github.ref == 'refs/heads/main'
    needs: pytest-job  # Only publish after tests are successful
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30

    steps:
    # Publish the package (if local `__version__` > pip version)
    - uses: etils-actions/pypi-auto-publish@v1
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        parse-changelog: true
